spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.50.202:3306/mocking?charset=utf8mb4&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  redis:
    host: 192.168.50.202
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis.xml
#日志
logging:
  config: classpath:logback-spring.xml
  path: /home/mocking