spring:
  datasource:
    url: jdbc:mysql://192.168.50.202:3306/mocking?charset=utf8mb4&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis.xml